### ISSUE TITLE
Hardcoded interface endpoint 0 not part of interface

### ISSUE THREAD

**Issue by cafca** [samccone/thermal_print#2]
I was able to make this lib work by changing the hardcoded interface endpoint in `driver.sendBytes` from 1 to 3:

```
export async function sendBytes(device: USBDevice, bytes: Uint8Array) {
  return device.transferOut(3, bytes);
}
```

For my printer this corresponds to the `out` endpoint.

```
endpoints: Array(2)
    0: USBEndpoint
        direction: "in"
        endpointNumber: 1
        packetSize: 64
        type: "bulk"
        __proto__: USBEndpoint
    1: USBEndpoint
        direction: "out"
        endpointNumber: 3
        packetSize: 64
        type: "bulk"
        __proto__: USBEndpoint
length: 2
__proto__: Array(0)
```

I am wondering if this should be dynamically selected instead of hardcoded but I don't know enough about WebUSB. If `sendBytes` should indeed choose the endpointNumber by selecting the endpoint with `direction: 'out'` I could make a PR.

**Comment by samccone** [comment]
oh yes.... this should 100% not be hard coded and instead should look to find the `out` endpoint.
@ciex if you are interested in making the PR it would be appreciated. Please do let me know if you have any questions.
